replicaCount: 1

image:
  repository: zanzibeer/admin-gui
  pullPolicy: Always
  tag: "dev"

resources: 
  requests:
    memory: "500Mi"
  limits:
    memory: "1Gi"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
#  type: NodePort
  type: ClusterIP
#  nodePort: 30803
  port: 80

configMap:
  LOGGING_FLUENTD_HOST: fluentd-aggregator.logging.svc
  SPRING_R2DBC_URL: "r2dbc:postgresql://postgres-db.default:5432/neofoundation_printingforms"
  SPRING_R2DBC_USERNAME: postgres
  SPRING_R2DBC_PASSWORD: testpassword

probes:
  enabled: false

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
