apiVersion: v1
kind: Service
metadata:
  name: {{ include "admin-gui.fullname" . }}
  labels:
    {{- include "admin-gui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "admin-gui.selectorLabels" . | nindent 4 }}
