apiVersion: v1
kind: Service
metadata:
  name: {{ include "admin-back.fullname" . }}
  labels:
    {{- include "admin-back.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "admin-back.selectorLabels" . | nindent 4 }}
