replicaCount: 1

image:
  repository: zanzibeer/admin-back
  pullPolicy: Always
  tag: "dev"

resources: 
  requests:
    memory: "500Mi"
  limits:
    memory: "1Gi"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
#  type: NodePort
  type: ClusterIP
#  nodePort: 30800
  port: 8080

configMap:
  LOGGING_FLUENTD_HOST: fluentd-aggregator.logging.svc

probes:
  enabled: false

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
